language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm install -g firebase-tools

script:
  - echo "Deploying"
  - npm run generate

after_success:
  - firebase deploy — project projectId --token $FIREBASE_TOKEN.